### ISSUE TITLE
Build error in Xcode - "Initializer for conditional binding must have Optional type, not "Color".

### ISSUE THREAD

**Issue by hryhoriiK97** [urbanairship/react-native-airship#503]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
 "urbanairship-react-native": "14.6.1"
  "react": "18.2.0",
  "react-native": "0.71.7",

### What are the versions of any relevant development tools you are using?

Xcode 14.3
# Report

### What unexpected behavior are you seeing?

The project doesn't build in Xcode and getting this error as on screenshot.

### What is the expected behavior?

The app should normally build and running with urbanairship-react-native plugin.

### What are the steps to reproduce the unexpected behavior?

Create a react-native project with version 0.71.7 and install "urbanairship-react-native": "14.6.1" and try to run the app.

### Do you have logging for the issue?
<img width="1179" alt="Zrzut ekranu 2023-04-26 o 12 00 45" src="https://user-images.githubusercontent.com/65455681/234543047-b2a774d8-5f8e-4b68-ad4c-048e572fd0a1.png">

**Comment by maurovisintin** [comment]
Same after updating to Xcode 14.3

**Comment by hryhoriiK97** [comment]
> Same after updating to Xcode 14.3

I have found a temporary solution , replace the rectangle function with this: 
```
@ViewBuilder
private static func rectangle(colorScheme: ColorScheme, border: Border?) -> some View {
    let strokeColor = border?.strokeColor?.toColor(colorScheme) ?? Color.clear
    let strokeWidth = border?.strokeWidth ?? 0
    let cornerRadius = border?.radius ?? 0
    
    if (cornerRadius > 0) {
        if strokeWidth > 0 {
            RoundedRectangle(cornerRadius: cornerRadius, style: .continuous)
                .strokeBorder(strokeColor, lineWidth: strokeWidth)
        } else {
            RoundedRectangle(cornerRadius: cornerRadius, style: .continuous)
                .fill(Color.clear)
        }
    } else {
        if strokeWidth > 0 {
            Rectangle()
                .strokeBorder(strokeColor, lineWidth: strokeWidth)
        } else {
            Rectangle().fill(Color.clear)
        }
    }
}
```

**Comment by rlepinski** [comment]
The code is already fixed in the underlying SDK 16.11 and in 15.x of the plugin.

**Comment by hryhoriiK97** [comment]
> The code is already fixed in the underlying SDK 16.11 and in 15.x of the plugin.

Thank you for the update! But I'm trying to upgrade the package to `"@ua/react-native-airship": "15.2.5"` and when I'm running the `pod install` I get this error as on the screenshot. I increase the higher minimum deployment target to 13.0 for my project, but I'm still getting this error and couldn't install the pods. Do you have an idea what is wrong?

<img width="852" alt="Zrzut ekranu 2023-05-5 o 13 20 47" src="https://user-images.githubusercontent.com/65455681/236444669-9f4ab2cb-6409-4c71-8ead-45394f98418b.png">
